TAGS = ['AGR',
        'AT',
        'AUX',
        'CC',
        'CD',
        'CDT',
        'COM',
        'DT',
        'IN',
        'JJ',
        'JJT',
        'H',
        'HAM',
        'MD',
        'MOD',
        'NN',
        'NNG',
        'NNGT',
        'NNP',
        'NNT',
        'POS',
        'PRP',
        'QW',
        'RB',
        'RBR',
        'REL',
        'VB',
        'WDT',
        'ZVL',
        'o',
        'u',
        'yyCM',
        'yyCLN',
        'yyLRB',
        'yyQUOT',
        'yyDOT',
        'yyDASH',
        'yyRRB',
        'yyEXCL',
        'yyQM',
        'yySCLN',
        'yyELPS'
        ]

ST = '<s>'
ET = '</s>'
